### ISSUE TITLE
panic: Logger uninitialized. names=[]

### ISSUE THREAD

**Issue by tsynik** [anacrolix/log#2]
@anacrolix after switching to v0.13.1 of anacrolix/log I have panic with dms from ssdp, here is log:
```
panic: Logger uninitialized. names=["ssdp" "192.168.8.6:1900"]

goroutine 116 [running]:
github.com/anacrolix/log.loggerCore.handle({0x0, {0x400003d220, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0}, {0x0}, {0x0, ...}, ...}, ...)
        /Users/nikk/go/pkg/mod/github.com/anacrolix/log@v0.13.1/logger-core.go:82 +0x1a4
github.com/anacrolix/log.loggerCore.lazyLog({0x0, {0x400003d220, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0}, {0x0}, {0x0, ...}, ...}, ...)
        /Users/nikk/go/pkg/mod/github.com/anacrolix/log@v0.13.1/logger-core.go:72 +0x1a4
github.com/anacrolix/log.loggerCore.LazyLogDefaultLevel(...)
        /Users/nikk/go/pkg/mod/github.com/anacrolix/log@v0.13.1/logger-core.go:59
github.com/anacrolix/log.Logger.Println({{0x0, {0x400003d220, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0}, {0x0}, {0x0, ...}, ...}}, ...)
        /Users/nikk/go/pkg/mod/github.com/anacrolix/log@v0.13.1/logger.go:69 +0x10c
github.com/anacrolix/dms/ssdp.(*Server).handle(0x400040a280, {0x4000abc000, 0x0, 0x5dc}, 0x4000ab40f0?)
        /Users/nikk/go/pkg/mod/github.com/tsynik/dms@v1.4.3/ssdp/ssdp.go:261 +0x390
created by github.com/anacrolix/dms/ssdp.(*Server).serve
        /Users/nikk/go/pkg/mod/github.com/tsynik/dms@v1.4.3/ssdp/ssdp.go:129 +0x1e8

```
added withNames() to ssdp.go - https://github.com/tsynik/dms/commit/05367d4ee4f459d71c674e1bcce7d73bd2d2a77f but this doesn't help. How to fix?

**Comment by tsynik** [comment]
hm, fixed this in dms/dms.go
